### ISSUE TITLE
French symbols not usable

### ISSUE THREAD

**Issue by alkeryn** [dhowland/EasyAVR#65] opened 2018-03-28 23:00 UTC
So i can't set altgr or éèçà and such others
even when pushing on my french keyboard the software don't recognize them ^^

**Comment by Synless** [comment] 2018-03-29 12:38
You have to use the dead keys on a english international keyboard for that (windows keyboard settings).
ç does not exist and is not supported on english-int , like all other unicodes : (

**Comment by dhowland** [comment] 2018-03-29 12:53
EasyAVR does not have internationalization support.  Keep in mind that keyboards don't, either.  It's the PC that interprets the special characters.  No matter which kind of keyboard you have, the key to the right of the spacebar sends the same scancode, no matter if it is labeled "Alt" or "AltGr".

**Comment by alkeryn** [comment] 2018-03-30 04:57
What i mean is that qmk have unicode character suport
and i'm not using windows ^^
https://docs.qmk.fm/feature_unicode.html
here
though i should maybe open an unicode support issue now
only realised after that there is no such keycode for "é" but there is an unicode for it

**Comment by dhowland** [comment] 2018-04-02 02:11
Duplicate of #35

**Closed as completed by dhowland** 2018-04-02 02:11 UTC
Labels: enhancement
